### PR TITLE
Pushing metadata from XIS to XSE

### PR DESCRIPTION
**Pull request by SHGODE**
Hi, @mattdrayer Opening a pull request for pushing XIS metadata to XSE.

### CODE REVIEW

**Review by jdiouf — APPROVED** [review]
Looks fine so far, nothing jumped out besides moving hardcoded values to configuration files in the next sprint.

**Review by mattdrayer — APPROVED** [review]
My OCD loves alphabetization!

**Comment by SHGODE** [comment]
@mattdrayer  I have one question: 
When we are pushing data to XSE right now we are using **unique_record_identifier** as ID. 
Is it good to use Metadata_key or metadata_hash as ID to Post data instead, so that in future updations in XSE will happen based on key or key_hash and not on uuid?

**Comment by mattdrayer** [comment]
I suppose the question we need to ask is, could there be two course metadata records having `unique_record_identifier` values, which should be viewed by the XSE as the same record.  If the two records should be considered the same record by XSE, then a more generalized identifier would need to be specified, such as `metadata_key`.  I don't think we would want to use `metadata_hash` because this can change based on a revision of, say, the description.  So it should be a key field, regardless.

**Comment by SHGODE** [comment]
@mattdrayer Yes, what you said makes sense. 
Let's consider the below scenario : (if we use UUID as ID in XSE)
We have one active record in XSE(record 1), but when if we want to update the same record we make record1 inactive in XIS and create a new one with active status and new UUID(key and hash remain same). Now, record1 is still active in XSE. We have no way to catch that record1 and delete that or inactive that. So when we will push data to XSE next time record 2 will get added in XSE with new uuid. But now we have both records in XSE which can cause issues.

If we use Key as ID in XSE then, record 1 is already there and if we push record 2 with key as ID then it will update the existing key and not create a new record. 

What do you think? Should I change the ID from UUID to Metadata_Key?

**Comment by mattdrayer** [comment]
Yes, it sounds like `metadata_key` would be the proper identifier to use in this scenario.

**Comment by KarenAJ** [comment]
> Yes, it sounds like `metadata_key` would be the proper identifier to use in this scenario.

I'm just curious if we want to use the key_hash or key value here. Does it matter?

**Comment by mattdrayer** [comment]
I don't think it matters -- if we feel there is a reason to obfuscate the key value for some reason, then the hash would make sense to use.  I suppose this could be a configurable option for the XIS operator.  We could default to key (or hash) and allow the choice to switch to the other.

**Review by KarenAJ — APPROVED** [review]
Approved!

**Pull request merged**
